import Ticket from "./Ticket";

const FLIGHTS_DATA = [
  {
    id: 1,
    flightNumber: "BA202",
    airline: "British Airways",
    source: "LHR",
    destination: "JFK",
    sourceTerminal: "T5",
    destinationTerminal: "T7",
    departureTime: "10:30 AM",
    arrivalTime: "1:30 PM",
    status: "Delayed",
    capacity: 250,
    availableSeats: 120,
    price: 45000,
  },
  {
    id: 2,
    flightNumber: "AA305",
    airline: "American Airlines",
    source: "JFK",
    destination: "LAX",
    sourceTerminal: "T8",
    destinationTerminal: "T4",
    departureTime: "8:00 PM",
    arrivalTime: "11:15 PM",
    status: "On Time",
    capacity: 200,
    availableSeats: 80,
    price: 38000,
  },
  {
    id: 3,
    flightNumber: "LH789",
    airline: "Lufthansa",
    source: "FRA",
    destination: "DXB",
    sourceTerminal: "T1",
    destinationTerminal: "T3",
    departureTime: "2:30 PM",
    arrivalTime: "11:25 PM",
    status: "Cancelled",
    capacity: 220,
    availableSeats: 0,
    price: 42000,
  },
  {
    id: 4,
    flightNumber: "EK203",
    airline: "Emirates",
    source: "DXB",
    destination: "JFK",
    sourceTerminal: "T3",
    destinationTerminal: "T4",
    departureTime: "6:30 PM",
    arrivalTime: "3:10 AM",
    status: "On Time",
    capacity: 300,
    availableSeats: 150,
    price: 50000,
  },
  {
    id: 5,
    flightNumber: "SQ318",
    airline: "Singapore Airlines",
    source: "SIN",
    destination: "LHR",
    sourceTerminal: "T2",
    destinationTerminal: "T5",
    departureTime: "9:45 AM",
    arrivalTime: "5:10 PM",
    status: "On Time",
    capacity: 280,
    availableSeats: 90,
    price: 47000,
  },
  {
    id: 6,
    flightNumber: "QR901",
    airline: "Qatar Airways",
    source: "DOH",
    destination: "SYD",
    sourceTerminal: "T1",
    destinationTerminal: "T3",
    departureTime: "3:00 AM",
    arrivalTime: "10:30 PM",
    status: "Delayed",
    capacity: 290,
    availableSeats: 110,
    price: 52000,
  },
  {
    id: 7,
    flightNumber: "DL404",
    airline: "Delta Airlines",
    source: "LAX",
    destination: "NRT",
    sourceTerminal: "T2",
    destinationTerminal: "T1",
    departureTime: "7:20 PM",
    arrivalTime: "12:15 AM",
    status: "On Time",
    capacity: 260,
    availableSeats: 75,
    price: 44000,
  },
  {
    id: 8,
    flightNumber: "CX101",
    airline: "Cathay Pacific",
    source: "HKG",
    destination: "LAX",
    sourceTerminal: "T1",
    destinationTerminal: "T5",
    departureTime: "11:10 AM",
    arrivalTime: "8:30 PM",
    status: "Delayed",
    capacity: 275,
    availableSeats: 95,
    price: 46000,
  },
  {
    id: 9,
    flightNumber: "AF207",
    airline: "Air France",
    source: "CDG",
    destination: "YUL",
    sourceTerminal: "T2",
    destinationTerminal: "T3",
    departureTime: "2:45 PM",
    arrivalTime: "6:30 PM",
    status: "On Time",
    capacity: 230,
    availableSeats: 100,
    price: 39000,
  },
  {
    id: 10,
    flightNumber: "JL123",
    airline: "Japan Airlines",
    source: "NRT",
    destination: "SFO",
    sourceTerminal: "T3",
    destinationTerminal: "T2",
    departureTime: "5:00 PM",
    arrivalTime: "9:30 AM",
    status: "On Time",
    capacity: 240,
    availableSeats: 85,
    price: 43000,
  },
];

export default function Flights({ selectedTicket, onTicketSelect }) {
  return (
    <div className=" overflow-y-scroll p-6 space-y-4 bg-primary-700">
      {FLIGHTS_DATA.map((flight) => (
        <Ticket
          key={flight.id}
          flight={flight}
          isSelected={selectedTicket?.id === flight.id}
          onSelect={onTicketSelect}
        />
      ))}
    </div>
  );
}
